version: "2"
run:
  concurrency: 4
  issues-exit-code: 1
  tests: true
linters:
  enable:
    - bodyclose
    - copyloopvar
    - containedctx
    - depguard
    - dogsled
    - dupl
    - err113
    - errorlint
    - exhaustive
    - errchkjson
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goprintffuncname
    - gosec
    - lll
    - misspell
    - mnd
    - noctx
    - nakedret
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - whitespace
    - wrapcheck
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          deny:
            - pkg: github.com/sirupsen/logrus
              desc: not allowed
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package
    dupl:
      # tokens count to trigger issue, 150 by default
      threshold: 100
    errcheck:
      # report about not checking of errors in type assertions: `a := b.(MyStruct)`;
      check-type-assertions: false
      # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(x)`;
      check-blank: false
    funlen:
      # Checks the number of lines in a function.
      # If lower than 0, disable the check.
      # Default: 60
      lines: 210
      # Checks the number of statements in a function.
      # If lower than 0, disable the check.
      # Default: 40
      statements: 55
      # Ignore comments when counting lines.
      # Default false
      ignore-comments: true
    goconst:
      min-len: 3
      min-occurrences: 3
    gocyclo:
      # minimal code complexity to report, 30 by default (but we recommend 10-20)
      min-complexity: 30
    gosec:
      excludes:
        # https://github.com/moby/moby/issues/48358
        # https://github.com/influxdata/telegraf/issues/15798
        - G115 # Potential integer overflow when converting between integer types
    govet:
      disable:
        - shadow
      enable-all: true
    lll:
      # max line length, lines longer will be reported. Default is 120.
      # '	' is counted as 1 character by default, and can be changed with the tab-width option.
      line-length: 150
      # tab width in spaces. Default to 1.
      tab-width: 1
    misspell:
      locale: US
    mnd:
      # List of enabled checks, see https://github.com/tommy-muehle/go-mnd/#checks for description.
      # Default: ["argument", "case", "condition", "operation", "return", "assign"]
      checks:
        - argument
        - case
        - condition
        - operation
        - return
        - assign
      ignored-files:
        - main.go
        - dashboards.go
        - sk8l.go
        - metrics.go
    nakedret:
      # make an issue when you have 3 or more consecutive return statements without parenthesis. Default is maxed at 1.
      max-func-lines: 1
    prealloc:
      # XXX: we don't recommend using this linter before doing performance profiling.
      # For most programs usage of prealloc will be a premature optimization.
      # Report preallocation suggestions only on simple loops that have no returns/breaks/continues/gotos in them.
      # True by default.
      simple: true
      # Report preallocation suggestions on range loops, but only if the range expression is constant.
      # True by default.
      range-loops: true
      # Report preallocation suggestions on for loops, but only for loops that have no returns/breaks/continues/gotos in them.
      # False by default.
      for-loops: false
    revive:
      max-open-files: 2048
      confidence: 0.8
      severity: warning
      enable-all-rules: true
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md
      rules:
        - name: add-constant
          severity: error
          disabled: true
        - name: argument-limit
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: atomic
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: banned-characters
          severity: warning
          disabled: true
          exclude:
            - ""
        - name: bare-return
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: blank-imports
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: bool-literal-in-expr
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: call-to-gc
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: cognitive-complexity
          arguments:
            - 60 # 7
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: confusing-naming
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: confusing-results
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: constant-logical-expr
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: context-as-argument
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: context-keys-type
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: cyclomatic
          arguments:
            - 20 # 10
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: datarace
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: deep-exit
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: defer
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: dot-imports
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: duplicated-imports
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: early-return
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: empty-block
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: empty-lines
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: enforce-map-style
          arguments:
            - any
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: enforce-repeated-arg-type-style
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: enforce-slice-style
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: error-naming
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: error-return
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: error-strings
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: errorf
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: exported
          severity: warning
          disabled: true
          exclude:
            - ""
        - name: flag-parameter
          severity: warning
          disabled: true
          exclude:
            - ""
        - name: function-result-limit
          arguments:
            - 4
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: function-length
          arguments:
            - 55
            - 210 # (int,int) the maximum allowed statements and lines
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: get-return
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: identical-branches
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: if-return
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: increment-decrement
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: indent-error-flow
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: import-alias-naming
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: imports-blocklist
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: import-shadowing
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: line-length-limit
          arguments:
            - 150
          severity: error
          disabled: false
          exclude:
            - ""
        - name: max-control-nesting
          arguments:
            - 4
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: max-public-structs
          arguments:
            - 3
          severity: warning
          disabled: true
          exclude:
            - ""
        - name: modifies-parameter
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: modifies-value-receiver
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: nested-structs
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: optimize-operands-order
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: package-comments
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: range
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: range-val-in-closure
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: range-val-address
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: receiver-naming
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: redundant-import-alias
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: redefines-builtin-id
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: string-of-int
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: superfluous-else
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: time-equal
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: time-naming
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: var-naming
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: var-declaration
          severity: warning
          disabled: false
        - name: unconditional-recursion
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: unexported-naming
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: unexported-return
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: unhandled-error
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: unnecessary-stmt
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: unreachable-code
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: unused-parameter
          severity: warning
          disabled: true
          exclude:
            - ""
        - name: unused-receiver
          severity: error
          disabled: true
          exclude:
            - ""
        - name: useless-break
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: waitgroup-by-value
          severity: warning
          disabled: false
          exclude:
            - ""
    unparam:
      check-exported: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - errcheck
          - gocyclo
          - gosec
          - revive
        path: _test\.go
      - linters:
          - gosec
        path: vendor/github.com/stretchr/testify/
      # https://staticcheck.dev/docs/checks
      - linters:
          - staticcheck
        text: SA9003 # Empty body in an if or else branch
      - linters:
          - staticcheck
        text: QF1008 # Omit embedded fields from selector expression
      - linters:
          - dupl
        text: lines are duplicate of
      - path: (.+)\.go$
        text: abcdef
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
