# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 1
project_name: sk8l-api
release:
  github:
    owner: danroux
    name: sk8l-api
  name_template: '{{.Tag}}'

# before:
#   hooks:
#     # You may remove this if you don't use go modules.
#     - go mod tidy
#     # you may remove this if you don't need go generate
#     - go generate ./...

builds:
  - id: sk8l-api
    main: main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    targets:
      - linux_amd64_v1
    skip: true

# git:
#   # What should be used to sort tags when gathering the current and previous
#   # tags if there are more than one tag in the same commit.
#   #
#   # Default: '-version:refname'
#   tag_sort: -version:creatordate

#   # What should be used to specify prerelease suffix while sorting tags when gathering
#   # the current and previous tags if there are more than one tag in the same commit.
#   #
#   # Since: v1.17
#   prerelease_suffix: "-"

#   # Tags to be ignored by GoReleaser.
#   # This means that GoReleaser will not pick up tags that match any of the
#   # provided values as either previous or current tags.
#   #
#   # Since: v1.21
#   # Templates: allowed
#   ignore_tags:
#     - nightly
#     - "{{.Env.IGNORE_TAG}}"

#   # Tags that begin with these prefixes will be ignored.
#   #
#   # This feature is only available in GoReleaser Pro.
#   # Since: v1.24 (pro)
#   # Templates: allowed
#   ignore_tag_prefixes:
#     - foo/
#     - "{{.Env.IGNORE_TAG_PREFIX}}/bar"
