apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    name: sk8l
  name: sk8l
  namespace: {{ .Values.namespace.name }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sk8l
  labels:
    name: sk8l
  namespace: {{ .Values.namespace.name }}
roleRef:
  kind: ClusterRole
  name: sk8l
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.metadata.name }}
    namespace: {{ .Values.namespace.name }}
