# https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html
# helm repo add eks https://aws.github.io/eks-charts
# helm repo update eks
# helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
#   -n kube-system \
#   --set clusterName=my-cluster \
#   --set serviceAccount.create=false \
#   --set serviceAccount.name=aws-load-balancer-controller
# kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller/crds?ref=master"
apiVersion: v1
kind: Service
metadata:
  name: "sk8l"
  namespace: {{ .Values.namespace.name }}
  annotations:
    {{- if .Values.service.annotations }}
    {{- toYaml .Values.service.annotations | nindent 4 }}
    {{ end }}
  labels:
    {{- if .Values.service.labels }}
    {{- toYaml .Values.service.labels | nindent 4 }}
    {{ end }}
spec:
  {{- if .Values.service }}
  type: {{ .Values.service.type }}
  {{ end }}
  {{- if .Values.service }}
  ports:
  {{- toYaml .Values.service.ports | nindent 4 }}
  {{ end }}
  selector:
    app.kubernetes.io/pod: sk8l-api
