// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CronjobClient is the client API for Cronjob service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CronjobClient interface {
	GetCronjobs(ctx context.Context, in *CronjobsRequest, opts ...grpc.CallOption) (Cronjob_GetCronjobsClient, error)
	GetCronjob(ctx context.Context, in *CronjobRequest, opts ...grpc.CallOption) (Cronjob_GetCronjobClient, error)
	GetCronjobPods(ctx context.Context, in *CronjobPodsRequest, opts ...grpc.CallOption) (Cronjob_GetCronjobPodsClient, error)
	GetJobs(ctx context.Context, in *JobsRequest, opts ...grpc.CallOption) (Cronjob_GetJobsClient, error)
	GetCronjobYAML(ctx context.Context, in *CronjobRequest, opts ...grpc.CallOption) (*CronjobYAMLResponse, error)
	GetJobYAML(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*JobYAMLResponse, error)
	GetPodYAML(ctx context.Context, in *PodRequest, opts ...grpc.CallOption) (*PodYAMLResponse, error)
	GetDashboardAnnotations(ctx context.Context, in *DashboardAnnotationsRequest, opts ...grpc.CallOption) (*DashboardAnnotationsResponse, error)
}

type cronjobClient struct {
	cc grpc.ClientConnInterface
}

func NewCronjobClient(cc grpc.ClientConnInterface) CronjobClient {
	return &cronjobClient{cc}
}

func (c *cronjobClient) GetCronjobs(ctx context.Context, in *CronjobsRequest, opts ...grpc.CallOption) (Cronjob_GetCronjobsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Cronjob_ServiceDesc.Streams[0], "/sk8l.Cronjob/GetCronjobs", opts...)
	if err != nil {
		return nil, err
	}
	x := &cronjobGetCronjobsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Cronjob_GetCronjobsClient interface {
	Recv() (*CronjobsResponse, error)
	grpc.ClientStream
}

type cronjobGetCronjobsClient struct {
	grpc.ClientStream
}

func (x *cronjobGetCronjobsClient) Recv() (*CronjobsResponse, error) {
	m := new(CronjobsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cronjobClient) GetCronjob(ctx context.Context, in *CronjobRequest, opts ...grpc.CallOption) (Cronjob_GetCronjobClient, error) {
	stream, err := c.cc.NewStream(ctx, &Cronjob_ServiceDesc.Streams[1], "/sk8l.Cronjob/GetCronjob", opts...)
	if err != nil {
		return nil, err
	}
	x := &cronjobGetCronjobClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Cronjob_GetCronjobClient interface {
	Recv() (*CronjobResponse, error)
	grpc.ClientStream
}

type cronjobGetCronjobClient struct {
	grpc.ClientStream
}

func (x *cronjobGetCronjobClient) Recv() (*CronjobResponse, error) {
	m := new(CronjobResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cronjobClient) GetCronjobPods(ctx context.Context, in *CronjobPodsRequest, opts ...grpc.CallOption) (Cronjob_GetCronjobPodsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Cronjob_ServiceDesc.Streams[2], "/sk8l.Cronjob/GetCronjobPods", opts...)
	if err != nil {
		return nil, err
	}
	x := &cronjobGetCronjobPodsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Cronjob_GetCronjobPodsClient interface {
	Recv() (*CronjobPodsResponse, error)
	grpc.ClientStream
}

type cronjobGetCronjobPodsClient struct {
	grpc.ClientStream
}

func (x *cronjobGetCronjobPodsClient) Recv() (*CronjobPodsResponse, error) {
	m := new(CronjobPodsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cronjobClient) GetJobs(ctx context.Context, in *JobsRequest, opts ...grpc.CallOption) (Cronjob_GetJobsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Cronjob_ServiceDesc.Streams[3], "/sk8l.Cronjob/GetJobs", opts...)
	if err != nil {
		return nil, err
	}
	x := &cronjobGetJobsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Cronjob_GetJobsClient interface {
	Recv() (*JobsResponse, error)
	grpc.ClientStream
}

type cronjobGetJobsClient struct {
	grpc.ClientStream
}

func (x *cronjobGetJobsClient) Recv() (*JobsResponse, error) {
	m := new(JobsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cronjobClient) GetCronjobYAML(ctx context.Context, in *CronjobRequest, opts ...grpc.CallOption) (*CronjobYAMLResponse, error) {
	out := new(CronjobYAMLResponse)
	err := c.cc.Invoke(ctx, "/sk8l.Cronjob/GetCronjobYAML", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronjobClient) GetJobYAML(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*JobYAMLResponse, error) {
	out := new(JobYAMLResponse)
	err := c.cc.Invoke(ctx, "/sk8l.Cronjob/GetJobYAML", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronjobClient) GetPodYAML(ctx context.Context, in *PodRequest, opts ...grpc.CallOption) (*PodYAMLResponse, error) {
	out := new(PodYAMLResponse)
	err := c.cc.Invoke(ctx, "/sk8l.Cronjob/GetPodYAML", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronjobClient) GetDashboardAnnotations(ctx context.Context, in *DashboardAnnotationsRequest, opts ...grpc.CallOption) (*DashboardAnnotationsResponse, error) {
	out := new(DashboardAnnotationsResponse)
	err := c.cc.Invoke(ctx, "/sk8l.Cronjob/GetDashboardAnnotations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CronjobServer is the server API for Cronjob service.
// All implementations must embed UnimplementedCronjobServer
// for forward compatibility
type CronjobServer interface {
	GetCronjobs(*CronjobsRequest, Cronjob_GetCronjobsServer) error
	GetCronjob(*CronjobRequest, Cronjob_GetCronjobServer) error
	GetCronjobPods(*CronjobPodsRequest, Cronjob_GetCronjobPodsServer) error
	GetJobs(*JobsRequest, Cronjob_GetJobsServer) error
	GetCronjobYAML(context.Context, *CronjobRequest) (*CronjobYAMLResponse, error)
	GetJobYAML(context.Context, *JobRequest) (*JobYAMLResponse, error)
	GetPodYAML(context.Context, *PodRequest) (*PodYAMLResponse, error)
	GetDashboardAnnotations(context.Context, *DashboardAnnotationsRequest) (*DashboardAnnotationsResponse, error)
	mustEmbedUnimplementedCronjobServer()
}

// UnimplementedCronjobServer must be embedded to have forward compatible implementations.
type UnimplementedCronjobServer struct {
}

func (UnimplementedCronjobServer) GetCronjobs(*CronjobsRequest, Cronjob_GetCronjobsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetCronjobs not implemented")
}
func (UnimplementedCronjobServer) GetCronjob(*CronjobRequest, Cronjob_GetCronjobServer) error {
	return status.Errorf(codes.Unimplemented, "method GetCronjob not implemented")
}
func (UnimplementedCronjobServer) GetCronjobPods(*CronjobPodsRequest, Cronjob_GetCronjobPodsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetCronjobPods not implemented")
}
func (UnimplementedCronjobServer) GetJobs(*JobsRequest, Cronjob_GetJobsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetJobs not implemented")
}
func (UnimplementedCronjobServer) GetCronjobYAML(context.Context, *CronjobRequest) (*CronjobYAMLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCronjobYAML not implemented")
}
func (UnimplementedCronjobServer) GetJobYAML(context.Context, *JobRequest) (*JobYAMLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobYAML not implemented")
}
func (UnimplementedCronjobServer) GetPodYAML(context.Context, *PodRequest) (*PodYAMLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPodYAML not implemented")
}
func (UnimplementedCronjobServer) GetDashboardAnnotations(context.Context, *DashboardAnnotationsRequest) (*DashboardAnnotationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDashboardAnnotations not implemented")
}
func (UnimplementedCronjobServer) mustEmbedUnimplementedCronjobServer() {}

// UnsafeCronjobServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CronjobServer will
// result in compilation errors.
type UnsafeCronjobServer interface {
	mustEmbedUnimplementedCronjobServer()
}

func RegisterCronjobServer(s grpc.ServiceRegistrar, srv CronjobServer) {
	s.RegisterService(&Cronjob_ServiceDesc, srv)
}

func _Cronjob_GetCronjobs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CronjobsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CronjobServer).GetCronjobs(m, &cronjobGetCronjobsServer{stream})
}

type Cronjob_GetCronjobsServer interface {
	Send(*CronjobsResponse) error
	grpc.ServerStream
}

type cronjobGetCronjobsServer struct {
	grpc.ServerStream
}

func (x *cronjobGetCronjobsServer) Send(m *CronjobsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Cronjob_GetCronjob_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CronjobRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CronjobServer).GetCronjob(m, &cronjobGetCronjobServer{stream})
}

type Cronjob_GetCronjobServer interface {
	Send(*CronjobResponse) error
	grpc.ServerStream
}

type cronjobGetCronjobServer struct {
	grpc.ServerStream
}

func (x *cronjobGetCronjobServer) Send(m *CronjobResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Cronjob_GetCronjobPods_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CronjobPodsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CronjobServer).GetCronjobPods(m, &cronjobGetCronjobPodsServer{stream})
}

type Cronjob_GetCronjobPodsServer interface {
	Send(*CronjobPodsResponse) error
	grpc.ServerStream
}

type cronjobGetCronjobPodsServer struct {
	grpc.ServerStream
}

func (x *cronjobGetCronjobPodsServer) Send(m *CronjobPodsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Cronjob_GetJobs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JobsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CronjobServer).GetJobs(m, &cronjobGetJobsServer{stream})
}

type Cronjob_GetJobsServer interface {
	Send(*JobsResponse) error
	grpc.ServerStream
}

type cronjobGetJobsServer struct {
	grpc.ServerStream
}

func (x *cronjobGetJobsServer) Send(m *JobsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Cronjob_GetCronjobYAML_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CronjobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronjobServer).GetCronjobYAML(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sk8l.Cronjob/GetCronjobYAML",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronjobServer).GetCronjobYAML(ctx, req.(*CronjobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cronjob_GetJobYAML_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronjobServer).GetJobYAML(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sk8l.Cronjob/GetJobYAML",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronjobServer).GetJobYAML(ctx, req.(*JobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cronjob_GetPodYAML_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronjobServer).GetPodYAML(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sk8l.Cronjob/GetPodYAML",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronjobServer).GetPodYAML(ctx, req.(*PodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cronjob_GetDashboardAnnotations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DashboardAnnotationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronjobServer).GetDashboardAnnotations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sk8l.Cronjob/GetDashboardAnnotations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronjobServer).GetDashboardAnnotations(ctx, req.(*DashboardAnnotationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Cronjob_ServiceDesc is the grpc.ServiceDesc for Cronjob service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cronjob_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sk8l.Cronjob",
	HandlerType: (*CronjobServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCronjobYAML",
			Handler:    _Cronjob_GetCronjobYAML_Handler,
		},
		{
			MethodName: "GetJobYAML",
			Handler:    _Cronjob_GetJobYAML_Handler,
		},
		{
			MethodName: "GetPodYAML",
			Handler:    _Cronjob_GetPodYAML_Handler,
		},
		{
			MethodName: "GetDashboardAnnotations",
			Handler:    _Cronjob_GetDashboardAnnotations_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetCronjobs",
			Handler:       _Cronjob_GetCronjobs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetCronjob",
			Handler:       _Cronjob_GetCronjob_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetCronjobPods",
			Handler:       _Cronjob_GetCronjobPods_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetJobs",
			Handler:       _Cronjob_GetJobs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sk8l.proto",
}
