apiVersion: v2
name: sk8l
version: 0.22.0
appVersion: 0.21.0
description: |
  sk8l is a Cronjob/Job monitoring and visualization tool in Kubernetes. It enables users to monitor Cronjob/Job status by collecting metrics from the configured targets and publish them to prometheus.
icon: https://sk8l.io/charts/logo.png
keywords:
  - Cronjob
  - Monitoring
  - Observability
  - Metrics
  - Prometheus
home: https://sk8l.io
type: application
kubeVersion: ">=1.29.0-0"
sources:
  - "https://github.com/danroux/sk8l-api"
  - "https://github.com/danroux/sk8l-ui"
maintainers:
  - name: danroux
    email: dan@sk8l.io
    url: https://sk8l.io
annotations:
  artifacthub.io/images: |
    - name: sk8l-api
      image: danroux/sk8l-api:v0.18.0
    - name: sk8l-ui
      image: danroux/sk8l-ui:v0.18.0
    - name: envoy
      image: envoyproxy/envoy:v1.30-latest
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/changes: |
    - kind: changed
      description: "ci/dependabot: docker:(deps): bump alpine from 3.21.3 to 3.22.1"
    - kind: changed
      description: "ci/dependabot: docker:(deps): bump golang from 1.24.3 to 1.25.0"
    - kind: changed
      description: "ci/dependabot: gha:(deps): bump actions/checkout from 4.2.2 to 5.0.0"
    - kind: changed
      description: "ci/dependabot: gha:(deps): bump actions/setup-go from 5.4.0 to 5.5.0"
    - kind: changed
      description: "ci/dependabot: gha:(deps): bump azure/setup-helm from 4.3.0 to 4.3.1"
    - kind: changed
      description: "ci/dependabot: gha:(deps): bump docker/build-push-action from 6.16.0 to 6.18.0"
    - kind: changed
      description: "ci/dependabot: gha:(deps): bump docker/login-action from 3.4.0 to 3.5.0"
    - kind: changed
      description: "ci/dependabot: gha:(deps): bump docker/setup-buildx-action from 3.10.0 to 3.11.0"
    - kind: changed
      description: "ci/dependabot: gha:(deps): bump golangci/golangci-lint-action from 6.0.1 to 8.0.0"
    - kind: changed
      description: "ci/dependabot: go:(deps): bump google.golang.org/grpc from 1.72.0 to 1.72.1"
    - kind: changed
      description: "ci/dependabot: go:(deps): bump google.golang.org/grpc from 1.72.1 to 1.72.2"
    - kind: changed
      description: "ci/dependabot: go:(deps): bump k8s.io/client-go from 0.32.3 to 0.33.1"
    - kind: changed
      description: "misc: Improve logging, Improve dashboard layout and panel design, go refactorings: still a work in progress"
