apiVersion: v2
name: sk8l
version: 0.15.0
appVersion: 0.14.0
description: |
  sk8l is a Cronjob/Job monitoring and visualization tool in Kubernetes. It enables users to monitor Cronjob/Job status by collecting metrics from the configured targets and publish them to prometheus.
icon: https://sk8l.io/charts/logo.png
keywords:
  - Cronjob
  - Monitoring
  - Observability
  - Metrics
  - Prometheus
home: https://sk8l.io
type: application
kubeVersion: ">=1.26.0-0"
sources:
  - "https://github.com/danroux/sk8l-api"
  - "https://github.com/danroux/sk8l-ui"
maintainers:
  - name: danroux
    email: dan@sk8l.io
    url: https://sk8l.io
annotations:
  artifacthub.io/images: |
    - name: sk8l-api
      image: danroux/sk8l-api:v0.14.0
    - name: sk8l-ui
      image: danroux/sk8l-ui:v0.13.0
    - name: envoy
      image: envoyproxy/envoy:v1.30-latest
