name: Build & Push images

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
  # push:
  #   branches:
  #     - 'main'

jobs:
  sk8l-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - name: Checkout - set env
        run: echo "IMAGE_TAG=$(make version)" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push release version
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
        if: ${{ github.event_name != 'pull_request' && github.event_name != 'workflow_call' }}
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKERHUB_SK8L_API_IMAGE_NAME }}:latest
            ${{ vars.DOCKERHUB_SK8L_API_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      - name: Build and push dev version
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
        if: ${{ github.event_name == 'workflow_call' || github.event_name == 'pull_request' && inputs.image_tag }}
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKERHUB_SK8L_API_IMAGE_NAME }}:${{ inputs.image_tag }}
