name: Build & Push images

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
  push:
    branches:
      - 'main'
    tags:
      - '*'

permissions:
  packages: write

jobs:
  sk8l-api-dev-img:
    runs-on: ubuntu-latest
    name: sk8l-api:dev-${{ inputs.image_tag }}
    if: ${{ github.event_name == 'pull_request' && inputs.image_tag || github.event_name == 'workflow_call' }}
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Checkout - set env
        run: echo "IMAGE_TAG=$(make version)" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0
      - name: Login to Docker Hub
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push dev version to docker registry
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
        with:
          context: .
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            ${{ vars.DOCKERHUB_SK8L_API_IMAGE_NAME }}:dev-${{ inputs.image_tag }}
      - name: Login to ghcr.io
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push dev version to ghcr.io
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
        with:
          context: .
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            ${{ vars.GHCR_SK8L_API_IMAGE_NAME }}:dev-${{ github.sha }}
            ${{ vars.GHCR_SK8L_API_IMAGE_NAME }}:dev-${{ inputs.image_tag }}
  sk8l-image:
    runs-on: ubuntu-latest
    name: sk8l-api:tag | sk8l-api:latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Checkout - set env
        run: echo "IMAGE_TAG=$(make version)" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0
      - name: Login to Docker Hub
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push release version
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
        with:
          context: .
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            ${{ vars.DOCKERHUB_SK8L_API_IMAGE_NAME }}:latest
            ${{ vars.DOCKERHUB_SK8L_API_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
  sk8l-api-pre-img-main:
    runs-on: ubuntu-latest
    name: sk8l-api:pre-${{ github.sha }}
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0
      - name: Login to ghcr.io
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push pre version
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
        with:
          context: .
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            ${{ vars.GHCR_SK8L_API_IMAGE_NAME }}:pre
            ${{ vars.GHCR_SK8L_API_IMAGE_NAME }}:pre-${{ github.sha }}
