name: Build & Push images

on: workflow_dispatch
  # push:
  #   branches:
  #     - 'main'

jobs:
  production-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout - set env
        run: echo "IMAGE_TAG=$(make version)" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKERHUB_SK8L_API_IMAGE_NAME }}:latest
            ${{ vars.DOCKERHUB_SK8L_API_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
