name: k8s
on:
  pull_request:
    types: [opened, synchronize, labeled, reopened]

env:
  GO_VERSION: "1.22.2"

permissions:
  packages: write

jobs:
  docker-img:
    name: Build Docker image dev-${{ github.event.pull_request.number }}
    uses: ./.github/workflows/docker.yml
    with:
      image_tag: ${{ github.event.pull_request.number }}
    secrets: inherit
  k8s-tests:
    name: k8s ${{ matrix.k8s.version }}/pr#${{ github.event.pull_request.number }} tests
    needs: [docker-img]
    strategy:
      matrix:
        k8s:
          - version: v1.35.0
            image: "kindest/node:v1.35.0@sha256:452d707d4862f52530247495d180205e029056831160e22870e37e3f6c1ac31f"
          - version: v1.34.3
            image: "kindest/node:v1.34.3@sha256:08497ee19eace7b4b5348db5c6a1591d7752b164530a36f855cb0f2bdcbadd48"
          - version: v1.33.7
            image: "kindest/node:v1.33.7@sha256:d26ef333bdb2cbe9862a0f7c3803ecc7b4303d8cea8e814b481b09949d353040"
          - version: v1.32.11
            image: "kindest/node:v1.32.11@sha256:5fc52d52a7b9574015299724bd68f183702956aa4a2116ae75a63cb574b35af8"
          - version: v1.31.14
            image: "kindest/node:v1.31.14@sha256:6f86cf509dbb42767b6e79debc3f2c32e4ee01386f0489b3b2be24b0a55aac2b"
        kind:
          - version: "v0.31.0"
    uses: ./.github/workflows/k8s-test.yml
    with:
      image_tag: ${{ github.event.pull_request.number }}
      pull_request_number: ${{ github.event.pull_request.number }}
      kind_version: ${{ matrix.kind.version }}
      k8s_version: ${{ matrix.k8s.version }}
      k8s_image: ${{ matrix.k8s.image }}
