name: k8s
on:
  pull_request:
    types: [opened, synchronize, labeled, reopened]

env:
  GO_VERSION: "1.26.0"

permissions:
  packages: write

jobs:
  docker-img:
    name: Build Docker image dev-${{ github.event.pull_request.number }}
    uses: ./.github/workflows/docker.yml
    with:
      image_tag: ${{ github.event.pull_request.number }}
    secrets: inherit
  k8s-tests:
    name: k8s ${{ matrix.k8s.version }}/pr#${{ github.event.pull_request.number }} tests
    needs: [docker-img]
    strategy:
      matrix:
        k8s:
          - version: v1.37.0
            image: "kindest/node:v1.37.0@sha256:a1ed56cfb0e7b93589bdf97c8cd566405a265939e3620fc4f5de89adff580ae5"
          - version: v1.36.4
            image: "kindest/node:v1.36.4@sha256:099e049362a1526b2db71494e1947aae99bd16290d7c895f2b7ea312e3cbfaed"
          - version: v1.35.8
            image: "kindest/node:v1.35.8@sha256:07b2536e30b803ed61d1677a79df6115f798ce64c80f9e22f6ed45afd09323c0"
          - version: v1.34.11
            image: "kindest/node:v1.34.11@sha256:44e222ee2132dab25ff87301682f89eb82c7880ea3a1bf543bfe9708fd08d67d"
        kind:
          - version: "v0.33.0"
    uses: ./.github/workflows/k8s-test.yml
    with:
      image_tag: ${{ github.event.pull_request.number }}
      pull_request_number: ${{ github.event.pull_request.number }}
      kind_version: ${{ matrix.kind.version }}
      k8s_version: ${{ matrix.k8s.version }}
      k8s_image: ${{ matrix.k8s.image }}
