name: k8s
on:
  pull_request:
    types: [opened, synchronize, labeled, reopened]

env:
  GO_VERSION: "1.22.2"

permissions:
  packages: write

jobs:
  docker-img:
    name: Build Docker image dev-${{ github.event.pull_request.number }}
    uses: ./.github/workflows/docker.yml
    with:
      image_tag: ${{ github.event.pull_request.number }}
    secrets: inherit
  k8s-tests:
    name: k8s ${{ matrix.k8s.version }}/pr#${{ github.event.pull_request.number }} tests
    needs: [docker-img]
    strategy:
      matrix:
        k8s:
          - image: "kindest/node:v1.32.0@sha256:c48c62eac5da28cdadcf560d1d8616cfa6783b58f0d94cf63ad1bf49600cb027"
            version: v1.32.0
          - image: "kindest/node:v1.31.4@sha256:2cb39f7295fe7eafee0842b1052a599a4fb0f8bcf3f83d96c7f4864c357c6c30"
            version: v1.31.4
          - image: "kindest/node:v1.30.8@sha256:17cd608b3971338d9180b00776cb766c50d0a0b6b904ab4ff52fd3fc5c6369bf"
            version: v1.30.8
          - image: "kindest/node:v1.29.12@sha256:62c0672ba99a4afd7396512848d6fc382906b8f33349ae68fb1dbfe549f70dec"
            version: v1.29.12
        kind:
          - version: "v0.26.0"
    uses: ./.github/workflows/k8s-test.yml
    with:
      image_tag: ${{ github.event.pull_request.number }}
      pull_request_number: ${{ github.event.pull_request.number }}
      kind_version: ${{ matrix.kind.version }}
      k8s_version: ${{ matrix.k8s.version }}
      k8s_image: ${{ matrix.k8s.image }}
